# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [ ]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [ ]:
# TODO: Create a vector tensor
vector = torch.tensor([1,2,3,4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [ ]:
# TODO: Create a matrix tensor
matrix = torch.tensor ([[1,2,3 ],
                       [4,5,6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [3]:
import torch

# TODO: Create a 3D tensor
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [4]:
# TODO: Create random tensor
random_tensor = torch.rand(4,4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.7333, 0.0304, 0.4770, 0.2832],
        [0.0256, 0.7537, 0.8683, 0.4775],
        [0.2140, 0.4512, 0.9875, 0.7683],
        [0.0246, 0.1914, 0.0258, 0.3284]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [6]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3,224, 224)
print(image_tensor)

print(f"Shape: {image_tensor.shape}")

tensor([[[0.1839, 0.7874, 0.8856,  ..., 0.8775, 0.4725, 0.8751],
         [0.4853, 0.8154, 0.0096,  ..., 0.0209, 0.3321, 0.4841],
         [0.3613, 0.5743, 0.9006,  ..., 0.9228, 0.3905, 0.1903],
         ...,
         [0.1423, 0.2012, 0.5978,  ..., 0.8813, 0.4004, 0.3039],
         [0.7349, 0.6841, 0.5390,  ..., 0.1624, 0.9707, 0.1595],
         [0.7311, 0.5597, 0.0876,  ..., 0.8685, 0.0752, 0.2931]],

        [[0.8422, 0.4633, 0.3794,  ..., 0.9595, 0.4013, 0.0128],
         [0.0017, 0.5632, 0.7063,  ..., 0.3705, 0.4418, 0.8353],
         [0.9232, 0.3888, 0.4911,  ..., 0.1845, 0.2622, 0.1047],
         ...,
         [0.0356, 0.5268, 0.1588,  ..., 0.8107, 0.6412, 0.3743],
         [0.2557, 0.3309, 0.4447,  ..., 0.2135, 0.5832, 0.4456],
         [0.6257, 0.4109, 0.4897,  ..., 0.5342, 0.0099, 0.8125]],

        [[0.7746, 0.6292, 0.3172,  ..., 0.1911, 0.1405, 0.7635],
         [0.8551, 0.5057, 0.8444,  ..., 0.6374, 0.0470, 0.1535],
         [0.7481, 0.8824, 0.2093,  ..., 0.6282, 0.5521, 0.

## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [7]:
# TODO: Create zeros tensor
zeros = torch.zeros(5,5)
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [8]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones_like(random_tensor)
print(ones_like)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [9]:
# TODO: Create range tensor
range_tensor =  torch.arange(0,21,2)
print(range_tensor)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [16]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
print(float16_tensor)
print(int64_tensor)

tensor([1., 2., 3.], dtype=torch.float16)
tensor([1, 2, 3])


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [17]:
# TODO: Change dtype
float32_tensor = float16_tensor.type(torch.float32)
print(float32_tensor)

tensor([1., 2., 3.])


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [29]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2, 3, 4)
print(f"Tensor:\n{info_tensor}")
print(f"Shape: {info_tensor.shape}")
print(f"Dtype: {info_tensor.dtype}")
print(f"Device: {info_tensor.device}")

Tensor:
tensor([[[0.4032, 0.7967, 0.7343, 0.5259],
         [0.5571, 0.9763, 0.0148, 0.8342],
         [0.1991, 0.2919, 0.6992, 0.4244]],

        [[0.7964, 0.3408, 0.6416, 0.6325],
         [0.3347, 0.5365, 0.4679, 0.8551],
         [0.2725, 0.5833, 0.0138, 0.4040]]])
Shape: torch.Size([2, 3, 4])
Dtype: torch.float32
Device: cpu


In [38]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
added_tensor = tensor + 5
print(f"Added 5: {added_tensor}")

# TODO: Subtract 10
subtracted_tensor = tensor - 10
print(f"Subtracted 10: {subtracted_tensor}")

# TODO: Multiply by 2
multiplied_tensor = tensor * 2
print(f"Multiplied by 2: {multiplied_tensor}")

# TODO: Divide by 10
divided_tensor = tensor / 10
print(f"Divided by 10: {divided_tensor}")

Added 5: tensor([15, 25, 35])
Subtracted 10: tensor([ 0, 10, 20])
Multiplied by 2: tensor([20, 40, 60])
Divided by 10: tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [20]:
# TODO: Create A and B
A = torch.rand(2,3)
B = torch.rand(3,2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A,B)
print(result_mm)

# TODO: Matrix mul using @
result_at = torch.matmul(A,B)
print(result_at)

tensor([[1.5179, 1.2543],
        [1.1233, 0.8698]])
tensor([[1.5179, 1.2543],
        [1.1233, 0.8698]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [23]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
result_min = torch.min(agg_tensor)
print(result_min)
# TODO: Max
result_max = torch.max(agg_tensor)
print(result_max)
# TODO: Mean (note: may need to cast to float)
result_mean = torch.mean(agg_tensor.float())
print(result_mean)
# TODO: Sum
result_sum = torch.sum(agg_tensor)
print(result_sum)

tensor(0)
tensor(100)
tensor(50.)
tensor(5050)


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [37]:
# TODO: Argmin
result_argmin = torch.argmin(agg_tensor)
print(f"Argmin: {result_argmin}")

# TODO: Argmax
result_argmax = torch.argmax(agg_tensor)
print(f"Argmax: {result_argmax}")

Argmin: 0
Argmax: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [31]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
torch.reshape(reshape_tensor, (2,5))
reshaped = reshape_tensor.reshape(2, 5)
print(reshaped)
print(f"Original tensor shape: {reshape_tensor.shape}")
print(f"Reshaped tensor shape: {reshaped.shape}")

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
Original tensor shape: torch.Size([10])
Reshaped tensor shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [32]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
tensor_stacked_v = torch.stack([tensor1, tensor2], dim=0)
print("Vertical Stack:\n", tensor_stacked_v)

# TODO: Stack horizontally (dim=1)
tensor_stacked_h = torch.stack([tensor1, tensor2], dim=1)
print("Horizontal Stack:\n", tensor_stacked_h)

Vertical Stack:
 tensor([[[0.9471, 0.7219],
         [0.3263, 0.0419]],

        [[0.2577, 0.8772],
         [0.6053, 0.0292]]])
Horizontal Stack:
 tensor([[[0.9471, 0.7219],
         [0.2577, 0.8772]],

        [[0.3263, 0.0419],
         [0.6053, 0.0292]]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [34]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = torch.squeeze(squeeze_tensor)
print(squeezed)

# TODO: Unsqueeze on dim=0
unsqueezed = torch.unsqueeze(squeezed, dim=0)
print(unsqueezed)

tensor([0.8772, 0.8628, 0.7704])
tensor([[0.8772, 0.8628, 0.7704]])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [39]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = torch.permute(image_tensor, (1, 2, 0))
print(permuted)

tensor([[[0.0170, 0.8593, 0.5279],
         [0.3621, 0.7155, 0.2565],
         [0.9541, 0.4020, 0.8237],
         ...,
         [0.7542, 0.1801, 0.4704],
         [0.2458, 0.9330, 0.9215],
         [0.7938, 0.4675, 0.3607]],

        [[0.7336, 0.3208, 0.3039],
         [0.4301, 0.2913, 0.9959],
         [0.3374, 0.8606, 0.2826],
         ...,
         [0.5987, 0.8152, 0.5109],
         [0.9833, 0.2068, 0.6725],
         [0.9469, 0.2672, 0.3380]],

        [[0.3928, 0.0462, 0.7594],
         [0.0344, 0.9919, 0.5525],
         [0.3526, 0.9662, 0.6219],
         ...,
         [0.9218, 0.2391, 0.7279],
         [0.4371, 0.8575, 0.3472],
         [0.9190, 0.7567, 0.3562]],

        ...,

        [[0.3948, 0.4975, 0.9131],
         [0.5386, 0.6915, 0.7380],
         [0.7672, 0.2685, 0.6632],
         ...,
         [0.6073, 0.9707, 0.5524],
         [0.6335, 0.2041, 0.3987],
         [0.2510, 0.7202, 0.4331]],

        [[0.4635, 0.4048, 0.1625],
         [0.5351, 0.6374, 0.6248],
         [0.

## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [41]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
value_5 = index_tensor[0, 1, 1]
print(f" 5: Value{value_5}")

# TODO: Get second row [4,5,6]
second_row = index_tensor[0, 1]
print(f"Second row: {second_row}")

 5: Value5
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [42]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)
print(f"NumPy Array: {numpy_array}")
print(f"PyTorch Tensor: {from_numpy}")

NumPy Array: [1 2 3 4]
PyTorch Tensor: tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [43]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()
print(f"PyTorch Tensor: {pytorch_tensor}")
print(f"NumPy Array: {to_numpy}")

PyTorch Tensor: tensor([5, 6, 7, 8])
NumPy Array: [5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [44]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor
torch.manual_seed(77)
rand2 = torch.rand(2,2)

# Check equality
print(rand1 == rand2)

tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [46]:
# TODO: Set device
device = torch.device("cuda" if torch.cuda.is_available() else"cpu")

### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [48]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor = gpu_tensor.to(device)
print(gpu_tensor)
# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()
print(cpu_numpy)

tensor([10, 20, 30])
[10 20 30]
